apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deploy
spec:
  selector:
    matchLabels:
      app: myweb
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
        - name: hello-world
          image: kkkjeongwoo/mywebapp
          ports:
            - containerPort: 8080
